#removing NA Value for all variables 
CAC <- CAC %>% mutate(Age = ifelse(is.na(Age), "*", Age))
CAC <- CAC %>% mutate(Children = ifelse(is.na(Children), "*", Children))
CAC <- CAC %>% mutate(Conditions_Cancer = ifelse(is.na(Conditions_Cancer), "*", Conditions_Cancer))
CAC <- CAC %>% mutate(Conditions_Cardio_Disease = ifelse(is.na(Conditions_Cardio_Disease), "*", Conditions_Cardio_Disease))
CAC <- CAC %>% mutate(Conditions_Severe_Allergies = ifelse(is.na(Conditions_Severe_Allergies), "*", Conditions_Severe_Allergies))
CAC <- CAC %>% mutate(Conditions_Seizures = ifelse(is.na(Conditions_Seizures), "*", Conditions_Seizures))
CAC <- CAC %>% mutate(Conditions_Obesity = ifelse(is.na(Conditions_Obesity), "*", Conditions_Obesity))
CAC <- CAC %>% mutate(Conditions_Cardio_Disease = ifelse(is.na(Conditions_Cardio_Disease), "*", Conditions_Cardio_Disease))
CAC <- CAC %>% mutate(Conditions_Rheumatological = ifelse(is.na(Conditions_Rheumatological), "*", Conditions_Rheumatological))
CAC <- CAC %>% mutate(Conditions_Pulmonary = ifelse(is.na(Conditions_Pulmonary), "*", Conditions_Pulmonary))
CAC <- CAC %>% mutate(Conditions_Diabetes = ifelse(is.na(Conditions_Diabetes), "*", Conditions_Diabetes))
CAC <- CAC %>% mutate(Conditions_Immuno = ifelse(is.na(Conditions_Immuno), "*", Conditions_Immuno))
CAC <- CAC %>% mutate(Conditions_Pregnancy = ifelse(is.na(Conditions_Pregnancy), "*", Conditions_Pregnancy))
CAC <- CAC %>% mutate(Conditions_Other = ifelse(is.na(Conditions_Other), "*", Conditions_Other))
CAC <- CAC %>% mutate(Conditions_No_Conditions = ifelse(is.na(Conditions_No_Conditions), "*", Conditions_No_Conditions))
CAC <- CAC %>% mutate(Date= ifelse(is.na(Date), "*", Date))


[1] "Age"                                  
[2] "Children"                             
[3] "Children"                    
[4] "Conditions_Cardio_Disease"            
[5] "Conditions_Diabetes"                  
[6] "Conditions_Immuno"                    
[7] "Conditions_No_Conditions"             
[8] "Conditions_Obesity"                   
[9] "Conditions_Other"                     
[10] "Conditions_Pregnancy"                 
[11] "Conditions_Pulmonary"                 
[12] "Conditions_Rheumatological"           
[13] "Conditions_Seizures"                  
[14] "Conditions_Severe_Allergies"          
[15] "Date"                                 
[16] "Education"                            
[17] "Elderly_family"                       
[18] "Event"                                
[19] "Family_household"                     
[20] "Gender"                               
[21] "Health Insurance"                     
[22] "Income"                               
[23] "Language"                             
[24] "Number_children_1"                    
[25] "Number_children_2"                    
[26] "Number_children_3"                    
[27] "Number_elderly_1"                     
[28] "Number_elderly_2"                     
[29] "ParticipantID"                        
[30] "Question_1"                           
[31] "Question_10"                          
[32] "Question_11"                          
[33] "Question_12"                          
[34] "Question_13_Asymptomatic"             
[35] "Question_13_Congestion"               
[36] "Question_13_Cough"                    
[37] "Question_13_Diarrhea"                 
[38] "Question_13_Fatigue"                  
[39] "Question_13_Fever"                    
[40] "Question_13_Headache"                 
[41] "Question_13_Loss_of_Taste"            
[42] "Question_13_Muscle_Body_Aches"        
[43] "Question_13_Nausea"                   
[44] "Question_13_Other"                    
[45] "Question_13_Shortness_of_breath"      
[46] "Question_13_Sore_Throat"              
[47] "Question_14"                          
[48] "Question_15"                          
[49] "Question_16"                          
[50] "Question_17"                          
[51] "Question_18"                          
[52] "Question_19"                          
[53] "Question_2"                           
[54] "Question_20_Avoiding"                 
[55] "Question_20_Basic_Health"             
[56] "Question_20_COVID_19_Vacc"            
[57] "Question_20_Following_recommendations"
[58] "Question_20_Getting_tested"           
[59] "Question_20_Improving_ventilation"    
[60] "Question_20_Seeking"                  
[61] "Question_20_Staying_home"             
[62] "Question_21"                          
[63] "Question_22"                          
[64] "Question_23"                          
[65] "Question_24"                          
[66] "Question_25"                          
[67] "Question_26"                          
[68] "Question_27"                          
[69] "Question_28"                          
[70] "Question_29"                          
[71] "Question_3"                           
[72] "Question_30_Community_Health_Advocate"
[73] "Question_30_Community_Member"         
[74] "Question_30_Nurse_Practitioner"       
[75] "Question_30_Other"                    
[76] "Question_30_Physician"                
[77] "Question_30_Registered_Nurse"         
[78] "Question_31"                          
[79] "Question_32"                          
[80] "Question_33"                          
[81] "Question_34"                          
[82] "Question_35"                          
[83] "Question_36"                          
[84] "Question_37"                          
[85] "Question_38_Barbershop"               
[86] "Question_38_Church_service"           
[87] "Question_38_Community_Health_Advocate"
[88] "Question_38_Community_members"        
[89] "Question_38_Handout_flier"            
[90] "Question_38_Others"                   
[91] "Question_38_Social_media"             
[92] "Question_38_Standard_media"           
[93] "Question_39"                          
[94] "Question_4"                           
[95] "Question_40"                          
[96] "Question_41"                          
[97] "Question_42"                          
[98] "Question_43"                          
[99] "Question_44"                          
[100] "Question_45"                          
[101] "Question_46"                          
[102] "Question_47"                          
[103] "Question_48"                          
[104] "Question_49"                          
[105] "Question_5"                           
[106] "Question_50"                          
[107] "Question_51"                          
[108] "Question_52"                          
[109] "Question_53"                          
[110] "Question_54"                          
[111] "Question_55"                          
[112] "Question_56"                          
[113] "Question_57"                          
[114] "Question_58"                          
[115] "Question_59"                          
[116] "Question_6"                           
[117] "Question_60"                          
[118] "Question_61"                          
[119] "Question_62"                          
[120] "Question_63"                          
[121] "Question_64"                          
[122] "Question_65"                          
[123] "Question_66"                          
[124] "Question_67"                          
[125] "Question_68"                          
[126] "Question_69"                          
[127] "Question_7"                           
[128] "Question_70"                          
[129] "Question_71"                          
[130] "Question_72"                          
[131] "Question_73"                          
[132] "Question_74"                          
[133] "Question_75"                          
[134] "Question_76"                          
[135] "Question_77"                          
[136] "Question_78"                          
[137] "Question_8"                           
[138] "Question_9"                           
[139] "Race_Ethnicity"                       
[140] "Specifiy Language"                    
[141] "Specifiy Race"                        
[142] "Zip" 